<a href="https://colab.research.google.com/github/bray2020/AI-works/blob/main/Tensor%2CKeras_practice01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Linear Functions:
- The most common operation in neural network is to calculate the linear combination of the inputs, their weights and the biases. We can write the output like this: y = x*w+b
- Here w is the matrix of the weights 

# Weights and bias in Tensor:
- The aim of the neural network is to modify weights and bias in order to get the best prediction as the output
- Now to do that we will need tensor that can be modified (suppose, W is the matrix that contains the weights)
- So, we will need tf.Variable here. We will be able to change such tensor during runtime.

In [ ]:
#create a varaible tensor of shape (10,3)
import tensorflow as tf
rows = 10
features = 3
tf1 = tf.Variable(tf.ones([rows,features]))
tf1.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

#### How to get the probability values using tensor?
- softmax gives the probability value for the given input logit values

In [ ]:
tf.nn.softmax([1.2,0.9,0.4])   # softmax gives the probability value for the given input logit values

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.45659032, 0.3382504 , 0.20515925], dtype=float32)>

In [ ]:
tf.reduce_sum([1,2,3,1])

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Calculate natural log:

In [ ]:
tf.keras.__version__

'2.4.0'

Generate random values in a tensor:

In [ ]:
tf.random.normal((2,4))                     # normal distribution

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-2.5424743 , -2.285726  , -1.2451997 , -1.3150425 ],
       [ 0.71223736, -0.6257785 ,  0.92731684, -1.9431417 ]],
      dtype=float32)>

In [ ]:
tf.random.normal((2,4), mean=0, stddev=1)    # standard normal distribution

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.62630904,  1.6749508 , -1.2063437 , -0.56558347],
       [ 0.7344349 ,  1.434644  ,  0.6992289 , -3.7895994 ]],
      dtype=float32)>

# Tensor flow built-in data types:
- It has a very large number of data types
- tf.int16 : 16-bit signed integer 
- tf.int32 : 32-bit signed integer 
- tf.int64 : 64-bit signed integer 

# Tensor reshaping

In [ ]:
tf1 = tf.Variable([[[10,11,12],[13,14,15]],[[16,17,19],[19,21,35]]])
tf1

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 14, 15]],

       [[16, 17, 19],
        [19, 21, 35]]], dtype=int32)>

In [ ]:
print(tf.rank(tf1).numpy())

3


Now reshape it to a shape(2,6)

In [ ]:
tf.reshape(tf1, (2,6))

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 19, 19, 21, 35]], dtype=int32)>

In [ ]:
tf1 = tf.Variable([[[10,11,12],[13,14,15]],[[16,17,19],[19,21,35]]])
tf.reshape(tf1, (3,-1))               # -1 at the column position automatically selects the required column value

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [19, 19, 21, 35]], dtype=int32)>

Transpose:

In [ ]:
x = tf.reshape(tf1, (2,6))
print(x)
tf.transpose(x)

tf.Tensor(
[[10 11 12 13 14 15]
 [16 17 19 19 21 35]], shape=(2, 6), dtype=int32)


<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[10, 16],
       [11, 17],
       [12, 19],
       [13, 19],
       [14, 21],
       [15, 35]], dtype=int32)>

Average or Mean:

In [ ]:
v = tf.constant([[8.,9.],[1.,2.]])
print(v.numpy())

[[8. 9.]
 [1. 2.]]


In [ ]:
tf.reduce_mean(v).numpy()                # overall mean

5.0

In [ ]:
r1 = tf.reduce_mean(v, axis=0).numpy()   # row wise mean
print(r1)
r2 = tf.reduce_mean(v, axis=1).numpy()   # row wise mean
print(r2)

[4.5 5.5]
[8.5 1.5]


# Neural Network Model Building using Keras

## Keras:
- import the mnist dataset, handwritten dataset of digits
- This is a dataset of 60,000 28x28 grayscale images of the 10 digits, along with a test set of 10,000 images.

In [ ]:
data = tf.keras.datasets.mnist

In [ ]:
data.load_data()    # load the data

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

- split the loaded data

In [ ]:
#split the loaded data
(train_x,train_y), (test_x,test_y) = data.load_data()

In [ ]:
print(train_x.shape)
print(test_x.shape)

(60000, 28, 28)
(10000, 28, 28)


#### Defining the variables: epochs and batch_size
- Epochs represents the number of times we will send the full dataset through the ANN. 
- Batch_size is the number of observations after which the weights will be updated.

In [ ]:
#Defining the variables: epochs and batch_size
epochs = 10
batch_size = 32

In [ ]:
#Now normalize the data points and convert those into float data type
#Here dividing all the data points by 255.0 to convert the all data into greyscale(black and white)
#'RGB' (Red-Green-Blue) data points are being converted into greyscale(black and white)
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)

#cast the labels to int64
train_y, test_y = tf.cast(train_y, tf.int64), tf.cast(test_y, tf.int64)

In [ ]:
#check the train output
train_y       

<tf.Tensor: shape=(60000,), dtype=int64, numpy=array([5, 0, 4, ..., 5, 6, 8])>

- So there are total 60000 data points in the train set
- The output/label is of int64 data type
- And the output value will give always be from 0 to 9 as there are 10 digits only

In [ ]:
#check the test set output
test_y

<tf.Tensor: shape=(10000,), dtype=int64, numpy=array([7, 2, 1, ..., 4, 5, 6])>

- So there are total 10000 data points in the test set

## Build a sequential Neural Netwrork Model using this data
- In order to get the parameters like - how many dense leyers to generate, how many neurons should be in each layer etc can be found by doing hyper parameter tuning using GridSearchCV

In [ ]:
model1 = tf.keras.models.Sequential(
[tf.keras.layers.Flatten(),                                 #Flatten the input data 
 tf.keras.layers.Dense(512, activation=tf.nn.relu),         #Total hidden layers to generate 512, activation function used 'relu'
 tf.keras.layers.Dropout(0.2),                               
 tf.keras.layers.Dense(10, activation=tf.nn.softmax)]       #10 neurons for 10 class/label prediction
)

- 'tf.keras.models.Sequential' as we are building a sequemtial neural network
- 'tf.keras.layers.Flatten()' to flatten all the input data. Suppose the input data is of shape=(mxn), flatten will make it as shape = (m,) or (m,1)
- 'tf.keras.layers.Dense(512, activation=tf.nn.relu)', we are creating the network with total 512 neurons. And activation function used is 'relu'
- 'tf.keras.layers.Dropout(0.2)', dropping 20% of the netwrok randomly and work with the rest of the netwrok
-  'tf.keras.layers.Dense(10, activation=tf.nn.softmax)', Finally we are creating the output layer. As there are 10 target/label (0 to 9) so we have given 10 here. And the activation func used is 'softmax', it will give the probability value for all the class/labels

## Compile the Model
#### What is Compile?
- Compiling is basically applying an optimization algo to the whole neural network. The first parameter is the algo we want to use to get the optimal set of weights in the neural network. The algo used here is Adam.

#### Why Need optimizer?
- Optimizers are algorithms or methods used to change the attributes of the neural network such as weights, learning rate to reduce the losses/errors. Optimizers are used to solve optimization problems by minimizing the function.
- Optimization algorithms are responsible for reducing the losses and to provide the most accurate results possible.

In [ ]:
optimizer = tf.keras.optimizers.Adam() 
model1.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

## Fit the model with train data

In [ ]:
model1.fit(train_x, train_y, batch_size=32, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.3641 - accuracy: 0.8922
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1017 - accuracy: 0.9700
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0678 - accuracy: 0.9789
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0500 - accuracy: 0.9836
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0386 - accuracy: 0.9870


- Not above that for the 1st epoch the loss is highest and accuracy is the lowest
- With each epoch the loss is getting decreased and the accuracy is increasing

In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (32, 784)                 0         
_________________________________________________________________
dense (Dense)                (32, 512)                 401920    
_________________________________________________________________
dropout (Dropout)            (32, 512)                 0         
_________________________________________________________________
dense_1 (Dense)              (32, 10)                  5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


## Evaluate The Model

In [ ]:
model1.evaluate(test_x, test_y)

313/313 [==============================] - 1s 3ms/step - loss: 0.0666 - accuracy: 0.9803


[0.06658080965280533, 0.9803000092506409]