<a href="https://colab.research.google.com/github/bray2020/AI-works/blob/main/Tensorflow01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AI Class01 : TensorFlow

In [83]:
print('1st AI Class')

1st AI Class


In [1]:
import tensorflow as tf   # import tensorflow and give it a alias

In [ ]:
tf.__version__            # check the version of it

'2.4.1'

Tensor Creation:
- A tensorflow which is nothing but a container that stores data, mostly deal with numerical data.
- It has 3 attributes - rank/axes/dimensions, shape and data type.

zero dimensional tensor creation:

In [21]:
t1 = tf.constant(1)    # create a tensor with a constant value 1
t1

<tf.Tensor: shape=(), dtype=int32, numpy=1>

- So, we have created a tensorflow that stores int32 data only.
- It has shape 0 (as it is just a single constant value). As it is just a single point , therefore is has zero dimension in the coordinate system.
- It has data type of int32 (32 bit integer, i.e 4 bytes) 
- The value is 1
- numpy=1 indicates the value=1

In [23]:
t1.numpy()    # here numpy() is a function, if we wish to see the values we need to use it

1

one dimensional tensor creation:

In [86]:
t2 = tf.constant([2,3,1,5])     # creating a one-dimensional tensor
t2                              

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 5], dtype=int32)>

- Here shape=(4,) means the tensor is a  1-dimensional array and there are total 4 elelemnts in that array.
- To be more specific, it is a 1-dimensional Vector (A row vector) 

two dimensional tensor creation:

In [25]:
t3 = tf.constant([[2,4,1,3],[3,2,1,4]])
t3

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 4, 1, 3],
       [3, 2, 1, 4]], dtype=int32)>

- Here shape=(2, 4) means that it is a 2-dimensional tensor with total numebr of rows=2 and total number of columns=4
- As this is a two-dimensional tensor , it can be considered as a Matrix

Three dimensional tensor creation:

In [87]:
t4=tf.constant([[[2,4,1,3],[3,4,1,2],[3,5,6,7]],[[3,4,0,2],[0,2,1,4],[0,3,5,7]],[[1,0,1,3],[5,0,1,2],[3,0,6,9]]])
t4

<tf.Tensor: shape=(3, 3, 4), dtype=int32, numpy=
array([[[2, 4, 1, 3],
        [3, 4, 1, 2],
        [3, 5, 6, 7]],

       [[3, 4, 0, 2],
        [0, 2, 1, 4],
        [0, 3, 5, 7]],

       [[1, 0, 1, 3],
        [5, 0, 1, 2],
        [3, 0, 6, 9]]], dtype=int32)>

- It has shape = (3, 3, 4)
- This tensor t3 has 3 matrics in it and each having shape of (3,4)
- Therefore, the 1st '3' means the number of dimensions
- The 2nd '3' means the number of rows and '4' means the number of columns

In [ ]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

()
(4,)
(2, 4)
(3, 3, 4)


In [ ]:
print(tf.rank(t1).numpy())
print(tf.rank(t2).numpy())
print(tf.rank(t3).numpy())
print(tf.rank(t4).numpy())

0
1
2
3


Data type conversion here: 

In [ ]:
t1 = tf.constant([2,3.,5])
t1.numpy()

array([2., 3., 5.], dtype=float32)

In [26]:
t1 = tf.constant([2,3,5],tf.float32)    # tf.float32 is converting all the data into float type data
t1.numpy()

array([2., 3., 5.], dtype=float32)

Tensor creation with Variable values: 
- When need to modify the tensor in further steps then create it as Variable and not as constant.

In [28]:
tv1 = tf.Variable(4)
tv2 = tf.Variable([2,1,3,5])
tv3 = tf.Variable([[2,4,1,3],[3,2,1,4]])
tv4 = tf.Variable([[[2,4,1,3],[3,4,1,2],[3,5,6,7]],[[3,4,0,2],[0,2,1,4],[0,3,5,7]],[[1,0,1,3],[5,0,1,2],[3,0,6,9]]])

Now check the rank/dimensions for each above created tensors:

In [ ]:
print(tf.rank(tv1).numpy())
print(tf.rank(tv2).numpy())
print(tf.rank(tv3).numpy())
print(tf.rank(tv4).numpy())

0
1
2
3


Slicing operation: When we want to access only a particilar value or a portion of the tensor
- Syntax: [slice1 says which matric to retrieve, slice2 says which rows to retrieve from that matric, slice3 says which columns to retieve]. 
- Here the 3rd slice is optional and only required if we need to retrieve any particual columns.

Let's get the 1st row and all the columns from the tensor tv3

In [35]:
tv3[1,:].numpy()

array([3, 2, 1, 4], dtype=int32)

Let's get the 2nd row and all columns from the tensor tv4. OR, we can also say it get the 3rd matrix from the tensor tv4

In [88]:
tv4

<tf.Variable 'Variable:0' shape=(3, 3, 4) dtype=int32, numpy=
array([[[2, 4, 1, 3],
        [3, 4, 1, 2],
        [3, 5, 6, 7]],

       [[3, 4, 0, 2],
        [0, 2, 1, 4],
        [0, 3, 5, 7]],

       [[1, 0, 1, 3],
        [5, 0, 1, 2],
        [3, 0, 6, 9]]], dtype=int32)>

In [36]:
tv4[2,:].numpy()   

array([[1, 0, 1, 3],
       [5, 0, 1, 2],
       [3, 0, 6, 9]], dtype=int32)

In [ ]:
tv4[2,:,:].numpy()     # Or we can also do by this code

array([[1, 0, 1, 3],
       [5, 0, 1, 2],
       [3, 0, 6, 9]], dtype=int32)

- Let's get 1st row, all values of columns of 1st and 2nd only from tv4

In [90]:
tv4

<tf.Variable 'Variable:0' shape=(3, 3, 4) dtype=int32, numpy=
array([[[2, 4, 1, 3],
        [3, 4, 1, 2],
        [3, 5, 6, 7]],

       [[3, 4, 0, 2],
        [0, 2, 1, 4],
        [0, 3, 5, 7]],

       [[1, 0, 1, 3],
        [5, 0, 1, 2],
        [3, 0, 6, 9]]], dtype=int32)>

In [91]:
tv4[1,:,1:3]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 0],
       [2, 1],
       [3, 5]], dtype=int32)>

Create tensors of ones and zeroes

In [ ]:
on = tf.ones([4,4], tf.int32)
on

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [38]:
zero = tf.zeros([2,4,4])   # create a 2 dimensional tensor of zeros with shape (4,4) 
zero

<tf.Tensor: shape=(2, 4, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

Tensor broadcasting: Change the shape of a tensor, values will remain the same of the tensor
- The values within a tensor will be broadcasted so that it can have the given shape

In [40]:
print(t1)                    # tensor t1 shape is (3,), so it is a 1 dimensional array now

tf.Tensor([2. 3. 5.], shape=(3,), dtype=float32)


In [41]:
tf.broadcast_to(t1, [4,3])   # expand t1 with shape=(4,3) and the newly added elements will be the existing elements of t1 only

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[2., 3., 5.],
       [2., 3., 5.],
       [2., 3., 5.],
       [2., 3., 5.]], dtype=float32)>

In [45]:
ta = tf.broadcast_to(t1,[4,3])
ta1 = tf.Variable(ta)       # storing the broadcasted tensor ta, as a variable ta1 so that we can modify it in future if required.
ta1

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[2., 3., 5.],
       [2., 3., 5.],
       [2., 3., 5.],
       [2., 3., 5.]], dtype=float32)>

Tensor assign: Assign new value to the tensor
- We can assign multiple values using assign as well as a single value

assign multiple values to the existing tensor

In [43]:
tr = tf.constant([9.,1])
tr.numpy()

array([9., 1.], dtype=float32)

In [46]:
ta1[2,1:].assign(tr)    # change the 2nd row and columns staring from 1 to all of tensor ta1, with the value of tensor tr

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[2., 3., 5.],
       [2., 3., 5.],
       [2., 9., 1.],
       [2., 3., 5.]], dtype=float32)>

assign a single value to the existing tensor

In [99]:
ta1[3,1].assign(65.)    # assign value 65.0 to the 3rd row and 1st element

<tf.Variable 'UnreadVariable' shape=(4, 3) dtype=float32, numpy=
array([[ 2.,  3.,  5.],
       [ 2.,  3.,  5.],
       [ 2.,  9.,  1.],
       [ 2., 65.,  5.]], dtype=float32)>

Conditional checking in Tensor:

In [ ]:
ta1>5                   # check if any element of tensor ta1 is greater than 5:

<tf.Tensor: shape=(4, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])>

In [ ]:
ta1[ta1>5].numpy()      # which element of ta1 is satisfying the given condition  i.e ta1>5

array([9.], dtype=float32)

In [47]:
tf.where(ta1>5)        # Returns the position of that element only which has satisfied the condition

<tf.Tensor: shape=(1, 2), dtype=int64, numpy=array([[2, 1]])>

Tensor mathematical operations:

In [ ]:
a = tf.constant(3.)
b = tf.constant(4.)
print(a.numpy())
print(b.numpy())

3.0
4.0


In [ ]:
c = a+b
print(c)
d = a-b
print(d)
e = a*b
print(e)
f = a/b
print(f)
g = b%a
print(g)

tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(-1.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(0.75, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
c1 = tf.add(a,b)
print(c1)
c2 = tf.subtract(a,b)
print(c2)
c3 = tf.multiply(a,b)
print(c3)
c4 = tf.divide(a,b)
print(c4)

tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(-1.0, shape=(), dtype=float32)
tf.Tensor(12.0, shape=(), dtype=float32)
tf.Tensor(0.75, shape=(), dtype=float32)


In [108]:
x = tf.constant([1,2,3,4])
y = tf.ones([2,4],dtype=tf.int32)
print(x.numpy())
print(y.numpy())
res = tf.add(y[1,:], x)
print('The resultant tensor:',res.numpy())

[1 2 3 4]
[[1 1 1 1]
 [1 1 1 1]]
The resultant tensor: [2 3 4 5]


In [49]:
p = tf.pow(3,2)     # calculate 3 to the power 2
print(p)
exp = tf.exp(1.)    # the value of e is 2.7182817. Here, exp(1.) indicates = e to the power 1.0
print(exp)
sq = tf.sqrt(25.)   # calculate the square root of 25.0
print(sq)

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(2.7182817, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)


In [ ]:
exp = tf.exp(.5)     # calclulate e to the power 0.5
print(exp)

tf.Tensor(1.6487212, shape=(), dtype=float32)


Concatenate 2 tensors: We can concatenate tensors along axes
- tf.concat([c1,c2],1) indicates concatenating along column axis. So, no of columns in the resultant tensor will increase
- tf.concat([c1,c2],0) indicates concatenating along row axis. So, no of rows in the resultant tensor will increase
- The axis number depends on the dimension of the tensor, if we have a 3-D tensor, then we can concatenate along axis=2 also

In [109]:
c1 = tf.ones([3,3])
c2 = tf.zeros([3,2])
tf.concat([c1,c2],1)    # column wise concatenation

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]], dtype=float32)>

In [110]:
c1 = tf.ones([3,3])
c2 = tf.zeros([5,3])
tf.concat([c1,c2],0)     # row wise concatenation

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

Tensor Multiplication:
- Matrix multiplication by 'matmul' method : In matrix multiplication, the no of columns of the 1st matrix must be equal to the no of rows of the 2nd matrix
- Matrix multiplication by '*' operation: This is positional multiplication of the matrics. So the multiplication happens according to the element's same position. To perform this operation both the merics should be of the same order. Suppose 1 matrix is of order mxn, then the other matrix should also be of mxn order. 


In [112]:
c1 = tf.constant([[1,5,8],[-3,4,6]])
c2 = tf.constant([[5,7,0],[1,2,6],[4,10,-3]])
m1 = tf.matmul(c1,c2)
m1.numpy()


array([[42, 97,  6],
       [13, 47,  6]], dtype=int32)

- '*' operation on the matrics of same order (3x3)

In [ ]:
m1 = tf.constant([[1,2,3],[1,1,0],[1,2,3]])
m2 = tf.constant([[2,2,0],[1,1,0],[2,2,3]])
res = m1*m2    # 
print(res)

tf.Tensor(
[[2 4 0]
 [1 1 0]
 [2 4 9]], shape=(3, 3), dtype=int32)


- '*' operation on the matrics of same order (2x2)

In [117]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[8,10]])
(a*b).numpy()

array([[ 5, 12],
       [24, 40]], dtype=int32)

Extra Practices:

In [57]:
tf1 = tf.constant(3.)
tf2 = tf.Variable(3)
tf.subtract(tf1,tf2)

InvalidArgumentError: ignored

- As data types are differet hence getting error

In [66]:
tf1 = tf.constant(3.)
tf2 = tf.cast(tf.Variable(3), tf.float32)    # change the data type from int32 to float32 and then apply subtraction 
tf.subtract(tf1,tf2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [81]:
a = tf.constant(10)
b = tf.constant(2)
res = tf.subtract(tf.divide(a,b), 4)         # first do division of a & b. Then do subtract(result, 4)
res

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>