<a href="https://colab.research.google.com/github/bray2020/AI-works/blob/main/Transfer_Learning_with_Logistic_Regression_Complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.applications.xception import Xception, preprocess_input
from keras.preprocessing.image import load_img, img_to_array
import os
import glob
import numpy as np

In [2]:
model = Xception()
model.summary()

Model: "xception"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 299, 299, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 149, 149, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 149, 149, 32) 128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_conv1_act (Activation)   (None, 149, 149, 32) 0           block1_conv1_bn[0][0]            
___________________________________________________________________________________________

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
DATA_DIR = "/content/drive/MyDrive/Colab Notebooks/Tensorflow/waffle_pancakes"

## Step 1 : Preprocessing

In [5]:
def preprocess(im):
  im = img_to_array(im)
  im = np.expand_dims(im,axis=0)
  im = preprocess_input(im)
  return im[0]

## Step 2:
- Changing Working Directory so as to access the files of images
- Loop over all the file names
- Read each image
- Use preprocess() function written before to preprocess every image.
- Store all the images in a list
##### The above process has to be done 4 times for each of the following -
- Train images of Waffles
- Test images of Waffles
- Train images of Pancakes
- Test images of Pancakes

In [6]:
os.chdir(os.path.join(DATA_DIR,'train','waffles'))

In [7]:
waffle_train_img_names = glob.glob("*.png")

# to extract all the .png images
# to create a list of all the images from that directory
# which is waffle_pancake/train/waffles

In [8]:
waffle_train_img_names

['images_q=tbn_ANd9GcTM5HpF5czzgPAbyDbXCLfEKw5eAr9zLMVNwG8qn-ok41uWnQVk3Q.png',
 'images_q=tbn_ANd9GcTffJd34wXhzPkvFSA3is5jgwO73LuAxv10ELHRQiFaP_ZmlgU2vw.png',
 'images_q=tbn_ANd9GcQgOJREumsd5JFmoeia1xJX8zBmKqLadU20X07cvxQ1z9UIKpxZ.png',
 'images_q=tbn_ANd9GcQ9WZII-twMrgg-VUKvVSTuV8mMOZKW0jfkQTXQi31cxKHWSsDh.png',
 'images_q=tbn_ANd9GcRix3Jw1ZvOPn_WATgISqI7L_7efTUuJS6MdBAVAR_4M3JF513p.png',
 'images_q=tbn_ANd9GcSc1bArUGEYWw-VelGRwThqZoF1X--3drJ2HAG86uIlYaRbLxuj6A.png',
 'images_q=tbn_ANd9GcT_MyXxqR9ARuiJVof9r02OVkYSEsBGDoENH47bg_CEMobWPG8YFQ.png',
 'images_q=tbn_ANd9GcSVK4HlN7wVCam0-hN3_I0OblWkDzVFwkK7Kd6M-rARRXdyJXc1_Q.png',
 'images_q=tbn_ANd9GcSvLaT3FWjh1F1x1dGzYa3uev2WQIGLgvDigObZR2cBU8Er01mg.png',
 'images_q=tbn_ANd9GcRbZU_wvC5WshlHc36ZHFoZaAmLhHvzHEQfug8pmJpH8MKXbs7TTA.png',
 'images_q=tbn_ANd9GcQ-NiPrXBoHgnagfi-_gRiOAFFv5i7aMsFEJlIs_C7DRbI2YFIp.png',
 'images_q=tbn_ANd9GcTybbJYRC-3LHTEJOa5orwSsNVGIDCv33wGwV-Yp4U7Endbe5tjiA.png',
 'images_q=tbn_ANd9GcR2eFGukZIm3rcuHn9co5L5A6clhtO

In [9]:
len(waffle_train_img_names) #number of waffle images in training dataset

564

In [10]:
waffle_train = []
for i in waffle_train_img_names:
  im = load_img(i, target_size=(299,299,3))
  waffle_train.append(preprocess(im))
# for every image in the list we have to preprocess
# load the images
# preprocess the images 

In [11]:
waffle_train[0]

array([[[0.8039216 , 0.79607844, 0.85882354],
        [0.8117647 , 0.8039216 , 0.8666667 ],
        [0.8117647 , 0.8039216 , 0.8666667 ],
        ...,
        [0.70980394, 0.6313726 , 0.7019608 ],
        [0.70980394, 0.6313726 , 0.7019608 ],
        [0.70980394, 0.6313726 , 0.7019608 ]],

       [[0.8039216 , 0.79607844, 0.85882354],
        [0.8117647 , 0.8039216 , 0.8666667 ],
        [0.8117647 , 0.8039216 , 0.8666667 ],
        ...,
        [0.70980394, 0.6313726 , 0.7019608 ],
        [0.70980394, 0.6313726 , 0.7019608 ],
        [0.70980394, 0.6313726 , 0.7019608 ]],

       [[0.8117647 , 0.8039216 , 0.8666667 ],
        [0.8117647 , 0.8039216 , 0.8666667 ],
        [0.8117647 , 0.8039216 , 0.8666667 ],
        ...,
        [0.70980394, 0.6313726 , 0.7019608 ],
        [0.70980394, 0.6313726 , 0.7019608 ],
        [0.70980394, 0.6313726 , 0.7019608 ]],

       ...,

       [[0.8352941 , 0.7411765 , 0.75686276],
        [0.827451  , 0.7411765 , 0.77254903],
        [0.827451  , 0

In [12]:
os.chdir(os.path.join(DATA_DIR,'test','waffles'))
waffle_test_img_names = glob.glob("*.png")

In [13]:
waffle_test = []
for i in waffle_test_img_names:
  im = load_img(i, target_size=(299,299,3))
  waffle_test.append(preprocess(im))

In [14]:
len(waffle_test_img_names)

235

In [15]:
os.chdir(os.path.join(DATA_DIR,'train','pancakes'))
pancakes_train_img_names = glob.glob("*.png")

In [16]:
pancakes_train = []
for i in pancakes_train_img_names:
  im = load_img(i, target_size=(299,299,3))
  pancakes_train.append(preprocess(im))

In [17]:
len(pancakes_train_img_names)

177

In [18]:
os.chdir(os.path.join(DATA_DIR,'test','pancakes'))
pancakes_test_img_names = glob.glob("*.png")

In [19]:
pancakes_test = []
for i in pancakes_test_img_names:
  im = load_img(i, target_size=(299,299,3))
  pancakes_test.append(preprocess(im))  

In [20]:
len(pancakes_test_img_names)

154

## Step 3:
- Convert all four lists into numpy arrays
- Create a train_set by concatinating all waffle and pancake images of trained arrays. This will be treated as predictors or independent variables for classification problem.

In [21]:
# The list has to be converted into np array
# each list containing pixel value of the image
# as the inputs we want in form of tensors
waffle_train = np.array(waffle_train, dtype='float32')

In [22]:
waffle_test = np.array(waffle_test, dtype='float32')

In [23]:
pancakes_train = np.array(pancakes_train, dtype='float32')
pancakes_test = np.array(pancakes_test, dtype='float32')

In [24]:
# the training dataset should contain both classes
# so we are concatenating the train data
# its row wise concatenation
# 564 + 171
train = np.concatenate((waffle_train,pancakes_train),axis=0)

In [25]:
train.shape # we have converted the images into 4-D tensor

(741, 299, 299, 3)

## Create train_labels / Target
- While concatinating trained images, we know that the top-most observations are waffle images and bottom-most observations are pancake images
- Take waffle as class 0 and pancake as class 1.
waffle_train.shape[0] yields total number of images belonging to waffle class
pancakes_train.shape[0] yields total number of images belonging to pancake class
So multiplying these two with 0 and 1's respectively yield us the target set

In [26]:
y = [0]*waffle_train.shape[0] + [1]*pancakes_train.shape[0]
# 564 no of 0 s will be present and rest 179 no of 1s will be also present 
# in y

In [27]:
[0]*10 # we will get list of 10 o's

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [28]:
waffle_train.shape[0]
# so [0]*waffle_train.shape[0] will give us 564 0's

564

In [29]:
pancakes_train.shape[0]
# so [1]*pancakes_train.shape[0] will give us 171 1's

177

In [30]:
len(y)

741

In [31]:
y = np.array(y, dtype='float32')
# converting the list to np array

## Step 4: Create a base model
- Take pre-trained model Xception without its top layers (excluding dense layers, but keeping only convolutional layers)
- Use Average Pooling to flatten the last convolutional layer results in Xception
- Flattening here is required to make the pre-trained model compatible with our input images in numpy array format.

In [32]:
base_model = Xception(include_top=False, pooling='avg',input_shape=(299,299,3))

- as we remove the dense layer as in the output layer we will just get the feature map exrtracted from the model
- the 2048 we have to flatten to make sure its an appropriate input for next layer.

## Step 5 : Feature extraction
- use predict() to extract

In [33]:
train_features = base_model.predict(train)

In [39]:
train_features.shape  #2048 features extracted for every image in train set

(741, 2048)

In [35]:
train_features[0]

array([0.        , 0.10271581, 0.6756433 , ..., 0.24664666, 0.        ,
       0.18079539], dtype=float32)

## Step 6: Applying Classification
- Create an object of Logistic Regression class
- Call fit() function to build the classification model on training features and the target


In [42]:
from sklearn.linear_model import LogisticRegression
logit_clf = LogisticRegression()
logit_clf.fit(train_features, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Step 7: Prediction
- Create a test set by concatinating all waffle and pancake images from test array.
- Create the target y_test for testing data
- Extract image features from all test images using base model of convolutinal layers (pre-trained model)
- Use predict() function of the logistic regression classifier 
- Compute accuracy of the classification model


In [37]:
test = np.concatenate((waffle_test, pancakes_test), axis=0)
y_test = [0]*waffle_test.shape[0] + [1]*pancakes_test.shape[0]
y_test = np.array(y_test)

In [41]:
y_test.shape

(389,)

In [59]:
#predict using test set images
test_features = base_model.predict(test)  

In [60]:
test_features.shape

(389, 2048)

In [61]:
preds = logit_clf.predict(test_features)

In [62]:
#display the 0th test image
preds[0] 

0.0

In [64]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       235
           1       0.90      0.84      0.87       154

    accuracy                           0.90       389
   macro avg       0.90      0.89      0.90       389
weighted avg       0.90      0.90      0.90       389



In [65]:
# confusion matrix
from sklearn.metrics import confusion_matrix
confusion_mtx = confusion_matrix(y_test, preds) 
print(confusion_mtx)

[[221  14]
 [ 24 130]]


In [67]:
from sklearn import datasets, linear_model, metrics
print("Logistic Regression model accuracy(in %):", 
metrics.accuracy_score(y_test, preds)*100)

Logistic Regression model accuracy(in %): 90.23136246786633


In [70]:
from sklearn .metrics import roc_auc_score
auc = np.round(roc_auc_score(y_test, preds), 3) 
print("Auc for our test data is {}". format(auc))

Auc for our test data is 0.892
